CREATE ROLE indr LOGIN PASSWORD 'indr';
CREATE DATABASE palindr OWNER indr;
CREATE DATABASE palindr2 OWNER indr;
GRANT ALL PRIVILEGES ON DATABASE palindr TO indr;
GRANT ALL PRIVILEGES ON DATABASE palindr2 TO indr;
